import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { RegisterComponent } from './pages/register/register.component';
import { DashboardComponent } from './pages/dashboard/dashboard.component';
import { QrDisplayComponent } from './pages/qr-display/qr-display.component';
import { ScanComponent } from './pages/scan/scan.component';
import { ScannerComponent } from './pages/scanner/scanner.component';
import { EditProfileComponent } from './pages/edit-profile/edit-profile.component';
import { AboutComponent } from './pages/about/about.component';
import { ContactComponent } from './pages/contact/contact.component';
import { PrivacyComponent } from './pages/privacy/privacy.component';
import { AllVehiclesComponent } from './pages/all-vehicles/all-vehicles.component';
import { LoginComponent } from './pages/login/login.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'all-vehicles', component: AllVehiclesComponent },
  { path: 'qr', component: QrDisplayComponent },
  { path: 'scan-qr', component: ScannerComponent },
  { path: 'v/:vehicleId', component: ScanComponent },
  { path: 'edit-profile', component: EditProfileComponent },
  { path: 'about', component: AboutComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'privacy', component: PrivacyComponent },
  { path: '**', redirectTo: '' }
];
